# Generated by Django 3.2.5 on 2021-07-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
