# Generated by Django 3.2.5 on 2021-08-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0004_confessionreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='confessionrequest',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
